#
#  ### Params for Niryo One driver ###
#

#
#  Communication with motors
#

# Dynamixel bus
dxl_baudrate:         1000000
dxl_uart_device_name: "/dev/serial0"

# CAN bus
spi_channel:        0
spi_baudrate:       1000000
gpio_can_interrupt: 25

calibration_timeout: 40

#
#  Read/Write/Check frequencies
#  Those params have been chosen to get a good (connection performance + speed / CPU usage) ratio
#

ros_control_loop_frequency:              100.0

niryo_one_hw_check_connection_frequency: 2.0
publish_hw_status_frequency:             2.0
publish_software_version_frequency:      2.0
publish_learning_mode_frequency:         2.0
read_rpi_diagnostics_frequency:          0.25

dxl_hardware_control_loop_frequency:     100.0
dxl_hw_write_frequency:                  50.0
dxl_hw_data_read_frequency:              15.0
dxl_hw_status_read_frequency:            0.5

can_hardware_control_loop_frequency:     1500.0
can_hw_write_frequency:                  50.0
can_hw_check_connection_frequency:       3.0
